
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-dynamic
  description: the classic petstore API from swagger.io, pulled from a live endpoint.
spec:
  type: openapi
  lifecycle: production
  owner: tap-gui
  system: tap
  definition:
    $text: https://petstore.swagger.io/v2/swagger.yaml
