apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Default User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kapplegate
spec:
  profile:
    displayName: Kris Applegate
    email: kapplegate@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: zimina
spec:
  profile:
    displayName: Andrei Zimin
    email: zimina@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mstergianis
spec:
  profile:
    displayName: Michael Stergianis
    email: mstergianis@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jklassen
spec:
  profile:
    displayName: Jamie Klassen
    email: jklassen@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: brendac
spec:
  profile:
    displayName: Brenda Chan
    email: brendac@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: wmontoya
spec:
  profile:
    displayName: Waldir Montoya
    email: wmontoya@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ssisil
spec:
  profile:
    displayName: Scott Sissil
    email: ssisil@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [development]
