apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Default User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [default-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kapplegate
spec:
  profile:
    displayName: Kris Applegate
    email: kapplegate@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [default-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: zimina
spec:
  profile:
    displayName: Andrei Zimin
    email: zimina@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [default-team]
